# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Macaba
tagline:          'Engineer. Electronics, Software & Systems Design'
description:      'A collection of projects, hacks and ideas.'
url:              http://macaba.github.io
baseurl:          /

author:
  name:           'macaba'
  url:            https://github.com/macaba

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/macaba
